name: job1 merge pull request
run-name: ${{ github.actor }} is merging GitHub Actions 🚀 for job1
on: [push]
jobs:
  Explore-GitHub-Actions:
    if: true
    runs-on: ubuntu-latest
    steps:
      - run: env | sort